//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connected.ServiceModel.Cdn.Agents.SmtpService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Connected.ServiceModel.Cdn.Agents.SmtpService.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Over Run in TextOnly Record Data Type.
        /// </summary>
        internal static string BufferOverrun {
            get {
                return ResourceManager.GetString("BufferOverrun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection time out.
        /// </summary>
        internal static string ConnectionTimeout {
            get {
                return ResourceManager.GetString("ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Dns server set in Dns Query Component.
        /// </summary>
        internal static string DnsServerNotSet {
            get {
                return ResourceManager.GetString("DnsServerNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid domain name.
        /// </summary>
        internal static string ErrInvalidDomainName {
            get {
                return ResourceManager.GetString("ErrInvalidDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Record Type submitted to Dns Query Component.
        /// </summary>
        internal static string InvalidRecordType {
            get {
                return ResourceManager.GetString("InvalidRecordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure Querying DNS Server.
        /// </summary>
        internal static string QueryFail {
            get {
                return ResourceManager.GetString("QueryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue message expired. Returning to the queue..
        /// </summary>
        internal static string WrnExpired {
            get {
                return ResourceManager.GetString("WrnExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message could not be sent. Deadline passed. returning to the queue..
        /// </summary>
        internal static string WrnLifespan {
            get {
                return ResourceManager.GetString("WrnLifespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message does not exist. It might get deleted in the meantime..
        /// </summary>
        internal static string WrnMessageNotFound {
            get {
                return ResourceManager.GetString("WrnMessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message could not be sent in a specified period. Ping needed to wait another cycle..
        /// </summary>
        internal static string WrnPingNeeded {
            get {
                return ResourceManager.GetString("WrnPingNeeded", resourceCulture);
            }
        }
    }
}
